
package com.harlan.smonitor.notice.scsms.webserviceclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "sendInfo", targetNamespace = "http://ws.sitech.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendInfo {


    /**
     * 
     * @param pin
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:callService")
    @WebResult(targetNamespace = "http://ws.sitech.com")
    @RequestWrapper(localName = "callService", targetNamespace = "http://ws.sitech.com", className = "com.sitech.sms.CallService")
    @ResponseWrapper(localName = "callServiceResponse", targetNamespace = "http://ws.sitech.com", className = "com.sitech.sms.CallServiceResponse")
    public String callService(
            @WebParam(name = "pin", targetNamespace = "http://ws.sitech.com")
                    String pin);

}
